-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS escola.professores
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    nome character varying(128) NOT NULL,
    sobrenome character varying(128) NOT NULL,
    endereco character varying(128) NOT NULL,
    telefone character varying(16) NOT NULL,
    email character varying(64) NOT NULL,
    data_nascimento character varying(10) NOT NULL,
    nacionalidade character varying(2) NOT NULL,
    sexo "char" NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS escola.alunos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    nome character varying(128) NOT NULL,
    sobrenome character varying(128) NOT NULL,
    matricula integer NOT NULL,
    email character varying(64) NOT NULL,
    endereco character varying(128) NOT NULL,
    telefone character varying(16) NOT NULL,
    data_nascimento character varying(10) NOT NULL,
    nacionalidade character varying(2) NOT NULL,
    media_geral numeric(4, 2) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT matricula UNIQUE (matricula)
);

CREATE TABLE IF NOT EXISTS escola.cursos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    codigo integer NOT NULL,
    nome character varying(64) NOT NULL,
    tipo character varying(16) NOT NULL,
    maximo_alunos integer NOT NULL,
    id_professor bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS escola.matriculas
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_aluno integer NOT NULL,
    id_curso integer NOT NULL,
    media_aluno numeric(4, 2) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS escola.cursos
    ADD CONSTRAINT fk_cursos_professores FOREIGN KEY (id_professor)
    REFERENCES escola.professores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS escola.matriculas
    ADD CONSTRAINT fk_matricula_curso FOREIGN KEY (id_curso)
    REFERENCES escola.cursos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS escola.matriculas
    ADD CONSTRAINT fk_matricula_aluno FOREIGN KEY (id_aluno)
    REFERENCES escola.alunos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;